<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '32',
    'cat_name' => '专题文章',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '所有只有一张图片的文章，都放在这里面',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  2 => 
  array (
    'cat_id' => '31',
    'cat_name' => '销售政策',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '22',
    'cat_name' => '轮胎讲堂',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  4 => 
  array (
    'cat_id' => '17',
    'cat_name' => '主页底部文章',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '4',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '15',
    'cat_name' => '系统3',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '26',
    'cat_name' => '关于中杰',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '4',
    'cat_name' => '系统1',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  8 => 
  array (
    'cat_id' => '3',
    'cat_name' => '系统2',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  9 => 
  array (
    'cat_id' => '18',
    'cat_name' => '关于我们',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '17',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  10 => 
  array (
    'cat_id' => '19',
    'cat_name' => '购物指南',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '17',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  11 => 
  array (
    'cat_id' => '20',
    'cat_name' => '售后服务',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '17',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  12 => 
  array (
    'cat_id' => '21',
    'cat_name' => '支付方式',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '17',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
);
?>